### PR TITLE
Fix user composable integration with Sentry plugin

### LINKED ISSUE #3: Update session scope setting to use the useUser composable

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
Migrate from direct Vuex store.watch(state => state.session) to the useUser composable from Kolibri's public JavaScript API.

Changes:
- Import watch from Vue 2.7 composition API and useUser composable
- Replace store.watch on session state with watch on currentUserId
- Properly unwrap reactive values using .value accessor
- Handle logout by clearing Sentry user context with setUser(null)
- Maintain error watching via Vuex store (unchanged)

## References
Fixes #3

## Reviewer guidance
:robot: This was created by Claude Code. @rtibbles then reviewed the generated output, and did iterative rounds of updates before making it ready for review :robot:

### CODE REVIEW

File: kolibri_sentry_plugin/assets/src/module.js [hunk 1]
```diff
@@ -38,16 +39,26 @@ if (plugin_data.sentryDSN) {
...
-        facility_id: session.facility_id,
-        type: JSON.stringify(session.kind),
-      });
+
+  // Use the useUser composable to track user changes
+  const user = useUser();
+
+  // Watch for changes to the current user and update Sentry scope
+  watch(
+    () => user.currentUserId.value,
```
Comment (AlexVelezLl) [inline kolibri_sentry_plugin/assets/src/module.js:48]: I've always had in mind that, for watching the changes of just one reactive property, the most concise way is to send the property as the first argument, i.e., `watch(user.currentUserId, () => ...)`. Is using this getter function better in any way? Or is it just a matter of preference?

**Review by AlexVelezLl — APPROVED** [review]
Code changes look good to me!

File: kolibri_sentry_plugin/assets/src/module.js (hunk 1 above)
Comment (rtibbles) [reply kolibri_sentry_plugin/assets/src/module.js:48]: I think this is just a hangover from https://v2.vuejs.org/v2/api/#vm-watch - because I explicitly told Claude we were using Vue 2, it went with the most cautious approach, but your way is more concise, and more aligned with the Vue composition API documentation.
